### ISSUE TITLE
Nincs a kliensnek elküldve az "Update Tags" packet

### ISSUE THREAD

**Issue by 0x000006** [marvintheskid/mc-reverse-proxy#13]
**pluginok:** nincsenek
**verzió:** legújabb commit (49408314f5f6b4da7612c560c7881adf56e88ddf) win10-en buildelve
**kliens:** Vanilla 1.18.2
**szerver:** Paper 1.18.2

**Emiatt:**
- nem működnek az eszközök (ugyanolyan gyorsan ütöd vele ki a blokkokat mint kézzel)
- a láva úgy néz ki, mint a víz
- nem tudsz felmászni felmászható blokkokon
- nem tudsz vízben úszni
- még sok más

![2023-01-22_00 59 38](https://user-images.githubusercontent.com/56885523/213894736-81aed6cf-796a-43f2-ac25-b70378f0f6ca.png)
![2023-01-22_00 59 50](https://user-images.githubusercontent.com/56885523/213894743-f62c0177-1c67-4211-89bb-5f8ce98556c2.png)

**Comment by marvintheskid** [comment]
Pár problémáról ezek közül már tudok, csak jelenleg vannak fontosabb dolgok is amikkel foglalkoznom kell. Valamikor ha lesz időm ránézek.

**Comment by 0x000006** [comment]
Összetákoltam egy fixet #14-ben

**Comment by marvintheskid** [comment]
Mergeltem, köszi! Viszont a probléma valószínűleg mélyebben van, hiszen a proxy-nak alapból teljesen transzparensnek kéne lennie, vagyis packet definition-ok nélkül is működnie kellett volna.
