### ISSUE TITLE
Java jdk

### ISSUE THREAD

**Issue by thybor** [marvintheskid/mc-reverse-proxy#15]
Hi marvin!

I had a problem installing java jdk. When i tried
to build gradlew.bat with git, it said, "Couldn't find Java jdk file in the C:\------\jre1.8.0-321 directory. Try to download a valid Java jdk file". I downloaded a java jdk file, and
I put it into that directory, but it doesn't worked.
Please help me install that file, because i want to hack
Fyremc. (I am hungarian too)

**Comment by MrExplode** [comment]
Please refer to the automated distribution builds [here](https://github.com/skidek/proxy-ffi-dist). It was made for the very problem of people not being able to build the software properly, and retarded skids capitalising on this and releasing builds with added malware.
